---
title: About Me
author: Davis Vaughan
date: '2017-05-10'
slug: 'about'
---

### Who am I?

Hi! I'm Davis Vaughan. A Master's student studying Mathematical Finance at the University of North Carolina at Charlotte. I enjoy all things R, and love automating tasks with it. I'm also a coffee enthusiast, as most R users seem to be.

### What else?

I'm the other half of [Business Science](http://www.business-science.io/). We develop open source software for financial analysis. Check out the site to learn more, and feel free to contact us if you're interested in our consultant services.

I helped co-author two R packages with [Matt Dancho](https://github.com/mdancho84):

- [tidyquant](https://business-science.github.io/tidyquant/) - Bringing financial analysis to the tidyverse
- [timekit](https://business-science.github.io/timekit/) - A collection of tools for working with time series 

I'm also interested in Actuarial Science and Quantitative Finance. I'll be looking for job opportunities post graduation in May 2018.

_"Think different."_ - Steve Jobs

### Want to get in touch?

I'm always up for a conversation about R or Finance. Tweet at me [here](https://twitter.com/dvaughan32) or send me an email at _dvaughan@business-science.io_
